.catalog:
    name: Network Services
    version: v0.2.3
    minimum_rancher_version: v1.7.0
    questions:
    - variable: DNS_RECURSER_TIMEOUT
      label: Timeout for Rancher DNS Recurser
      description: Specify timeout in seconds for DNS Recurser.
      required: true
      default: 2
      type: int
